"""ECDSA over NIST P-256, with every layer written out from the standard.

Three things have to be right for a signature produced here to verify anywhere
else, and they fail in different ways.

The first is the curve arithmetic. A point on the short Weierstrass curve
``y^2 = x^3 + a*x + b`` over the prime field GF(p) is a pair ``(x, y)``; the
group operation is the chord-and-tangent construction, written here in affine
coordinates with an explicit representation for the point at infinity, because
the two degenerate cases -- adding a point to itself, and adding a point to its
own negation -- are exactly the cases a scalar multiplication runs into and a
casual implementation gets wrong. The scalar multiplication is double-and-add
and it *starts* from the point at infinity, so it must be able to hold it: a
running sum that cannot represent infinity will quietly compute k*G wrong the
first time an intermediate addition cancels.

The second is the signature equation. ECDSA signs a *hash*, and the hash is
first cut down to the bit length of the group order and read as an integer z.
The signature is ``(r, s)`` with ``R = k*G``, ``r = R.x mod n`` and
``s = k^-1 * (z + r*d) mod n``. The nonce ``k`` is an argument of :func:`sign`
rather than something drawn inside it, because the attack this project
demonstrates later is two signatures that share a ``k``; a signer that quietly
replaced the caller's nonce could not exhibit it, and a test could not pin the
published RFC 6979 nonce against the standard.

The third is the nonce itself. Reusing one, or drawing it from a weak source,
leaks the private key outright, so :func:`sign_deterministic` derives it the way
RFC 6979 prescribes: an HMAC-SHA-256 pseudorandom generator keyed by the private
key and the message hash, so the same key and message always give the same k and
no entropy is needed at signing time. The HMAC is built here on
``src/sha256.py`` rather than imported from ``src/hmac.py`` because this
module's contract admits only the SHA-256 primitive and the standard library.
"""

from __future__ import annotations

from .sha256 import sha256

# The P-256 domain parameters, from NIST SP 800-186 (the same numbers appear in
# SEC 2 as secp256r1 and in ANSI X9.62 as prime256v1). They are written as
# integers so the curve equation can be read straight off the module.
#
#   y^2 = x^3 + a*x + b   over GF(p)
#
# a is fixed at -3, which is the whole reason P-256 is fast: the doubling
# formula can be written with a cheap subtraction instead of a multiplication by
# an arbitrary constant. It is stored already reduced, as p - 3, so no modular
# reduction is needed when it is used.
P256_P = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
P256_A = P256_P - 3
P256_B = 0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B

# The base point G, of order n. The cofactor is 1, so the whole curve is one
# cyclic group generated by G and every point on it is a multiple of G.
P256_G = (
    0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296,
    0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5,
)

# The order of G. Every scalar is taken modulo this, and n*G is the point at
# infinity by definition.
P256_N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551


# ---------------------------------------------------------------------------
# Point arithmetic.
#
# A point is a tuple (x, y) of field elements, and the point at infinity -- the
# identity of the group -- is represented by None. None is used rather than a
# sentinel tuple so that an accidental arithmetic use fails loudly instead of
# silently producing a coordinate.
# ---------------------------------------------------------------------------


def _is_on_curve(point) -> bool:
    """Return whether ``point`` satisfies the curve equation.

    The point at infinity is on the curve by convention. Every other point must
    satisfy ``y^2 == x^3 + a*x + b`` modulo p; a point that does not is not a
    point of the group and any arithmetic with it is meaningless.
    """

    if point is None:
        return True
    x, y = point
    return (y * y - (x * x * x + P256_A * x + P256_B)) % P256_P == 0


def _point_negate(point):
    """Return the inverse of ``point``: the reflection across the x-axis.

    ``(x, y)`` maps to ``(x, -y)``; the point at infinity is its own inverse.
    Negation is used by the doubling path, where a point added to its own
    negation must give the identity rather than a division by zero.
    """

    if point is None:
        return None
    x, y = point
    return (x, (-y) % P256_P)


def _point_double(point):
    """Double ``point`` with the tangent line at the point.

    The slope is ``(3*x^2 + a) / (2*y)``. When ``y`` is zero the tangent is
    vertical and the result is the point at infinity -- that is the case the
    representation has to survive, since it is the one a scalar multiplication
    reaches when a partial sum cancels.
    """

    if point is None:
        return None
    x, y = point
    if y == 0:
        return None
    slope = (3 * x * x + P256_A) * pow(2 * y, -1, P256_P) % P256_P
    x3 = (slope * slope - 2 * x) % P256_P
    y3 = (slope * (x - x3) - y) % P256_P
    return (x3, y3)


def _point_add(left, right):
    """Add two points with the chord through them.

    The identity is handled first, then the two cases where the chord is not
    defined: equal x-coordinates with opposite y give the point at infinity,
    and equal x-coordinates with equal y are a doubling, which is delegated to
    :func:`_point_double`. The remaining case is an ordinary chord whose slope
    is ``(y2 - y1) / (x2 - x1)``.
    """

    if left is None:
        return right
    if right is None:
        return left
    x1, y1 = left
    x2, y2 = right
    if x1 == x2:
        # Same x. On a curve the two possible y values are y and -y, so either
        # this is a point plus its negation (the identity) or a doubling.
        if (y1 + y2) % P256_P == 0:
            return None
        return _point_double(left)
    slope = (y2 - y1) * pow((x2 - x1) % P256_P, -1, P256_P) % P256_P
    x3 = (slope * slope - x1 - x2) % P256_P
    y3 = (slope * (x1 - x3) - y1) % P256_P
    return (x3, y3)


def _scalar_mult(scalar: int, point):
    """Return ``scalar * point`` by double-and-add.

    ``result`` starts at the point at infinity and the addend walks the binary
    expansion of ``scalar`` from the least significant bit up, doubling at every
    step. The scalar is reduced modulo n first: the group has order n, so
    ``n * point`` is the identity and ``_scalar_mult(P256_N, P256_G)`` is None.
    """

    scalar %= P256_N
    result = None
    addend = point
    while scalar:
        if scalar & 1:
            result = _point_add(result, addend)
        addend = _point_double(addend)
        scalar >>= 1
    return result


# ---------------------------------------------------------------------------
# Hash handling.
# ---------------------------------------------------------------------------


def digest_to_int(digest: bytes) -> int:
    """Read a message digest as the integer ECDSA signs, ``z``.

    The digest is interpreted big-endian and, when it is longer than the group
    order, only its leftmost bits are kept. Signing, verifying and the
    nonce-reuse attack all have to agree on this conversion -- if the attack
    read ``z`` differently from the signer it would recover a wrong private key
    and look like a broken attack rather than a mismatched conversion -- so it
    is public and shared rather than repeated.
    """

    if not isinstance(digest, (bytes, bytearray, memoryview)):
        raise ValueError("the digest must be bytes")
    return _bits2int(bytes(digest), P256_N.bit_length())


def _bits2int(data: bytes, bit_length: int) -> int:
    """Read the leftmost ``bit_length`` bits of ``data`` as an integer.

    This is the conversion ECDSA applies to the message hash: the digest is
    interpreted big-endian and, when it is longer than the group order, only its
    leftmost bits are kept. For a 32-byte digest on P-256 (order bit length
    256) the shift is zero, but writing the general rule keeps the conversion
    correct for a longer hash such as SHA-512.
    """

    value = int.from_bytes(data, "big")
    excess = len(data) * 8 - bit_length
    if excess > 0:
        value >>= excess
    return value


# ---------------------------------------------------------------------------
# HMAC-SHA-256, built on the module's own SHA-256.
#
# RFC 6979 needs an HMAC; this module may import only src/sha256.py and the
# standard library, so the construction is spelled out here rather than taken
# from src/hmac.py. It is RFC 2104: the key is padded to the 64-byte block size
# and XORed with the inner and outer pads.
# ---------------------------------------------------------------------------

_HMAC_BLOCK_SIZE = 64


def _hmac_sha256(key: bytes, message: bytes) -> bytes:
    """Return the HMAC-SHA-256 of ``message`` under ``key``.

    A key longer than the block is hashed first, as RFC 2104 requires, then
    padded with zeros to exactly one block.
    """

    if len(key) > _HMAC_BLOCK_SIZE:
        key = sha256(key)
    key = key.ljust(_HMAC_BLOCK_SIZE, b"\x00")
    inner = bytes(byte ^ 0x36 for byte in key)
    outer = bytes(byte ^ 0x5C for byte in key)
    return sha256(outer + sha256(inner + message))


# ---------------------------------------------------------------------------
# RFC 6979 deterministic nonces.
# ---------------------------------------------------------------------------


def _rfc6979_candidates(private_key: "PrivateKey", digest: bytes):
    """Yield the RFC 6979 nonce candidates for this key and message, in order.

    The generator is the HMAC-DRBG of RFC 6979 section 3.2: K and V start at
    the all-zero and all-one strings, are seeded with the private key and the
    message hash, and then each iteration extends V into the candidate ``T``
    which is reduced with :func:`_bits2int`. A candidate that is zero or at
    least n is rejected and the generator is stepped again, which is the path
    the standard's retry rule describes. In practice the first candidate is
    always accepted; the loop exists so the construction is complete.
    """

    order = P256_N
    qlen = order.bit_length()
    rolen = (qlen + 7) // 8
    hlen = 32  # SHA-256 output length in bytes

    # int2octets(x) and bits2octets(h1). The message hash is reduced modulo the
    # order before it is fed in, which is why a hash is not used raw.
    x_octets = private_key.secret.to_bytes(rolen, "big")
    z1 = _bits2int(digest, qlen)
    h1_octets = (z1 % order).to_bytes(rolen, "big")

    v = b"\x01" * hlen
    k = b"\x00" * hlen
    k = _hmac_sha256(k, v + b"\x00" + x_octets + h1_octets)
    v = _hmac_sha256(k, v)
    k = _hmac_sha256(k, v + b"\x01" + x_octets + h1_octets)
    v = _hmac_sha256(k, v)

    while True:
        t = b""
        while len(t) < rolen:
            v = _hmac_sha256(k, v)
            t += v
        candidate = _bits2int(t[:rolen], qlen)
        if 1 <= candidate < order:
            yield candidate
        else:
            # Rejected: reseed the generator and try again.
            k = _hmac_sha256(k, v + b"\x00")
            v = _hmac_sha256(k, v)


def _rfc6979_nonce(private_key: "PrivateKey", digest: bytes) -> int:
    """Return the first RFC 6979 nonce for this key and message.

    Exposed for the tests, which pin it against the nonces the RFC publishes;
    signing goes through :func:`sign_deterministic` so the retry rule is
    honoured.
    """

    return next(_rfc6979_candidates(private_key, digest))


# ---------------------------------------------------------------------------
# The public interface, as frozen in INTERFACES.md.
# ---------------------------------------------------------------------------


class PublicKey:
    """A point of the P-256 group, checked to be on the curve at construction.

    The check happens once here rather than on every verify, so a caller cannot
    hand the verifier a coordinate that is not a group element and get a
    plausible answer out of arithmetic that was never defined.
    """

    def __init__(self, point: tuple[int, int]) -> None:
        if not (isinstance(point, tuple) and len(point) == 2):
            raise ValueError("a public key point must be a pair (x, y)")
        x, y = point
        if not (isinstance(x, int) and isinstance(y, int)):
            raise ValueError("the point coordinates must be integers")
        if not (0 <= x < P256_P and 0 <= y < P256_P):
            raise ValueError("the point coordinates must be field elements of P-256")
        if not _is_on_curve((x, y)):
            raise ValueError("the point is not on the P-256 curve")
        self._point = (x, y)

    @property
    def x(self) -> int:
        return self._point[0]

    @property
    def y(self) -> int:
        return self._point[1]

    def to_bytes(self) -> bytes:
        """Return the uncompressed point encoding ``0x04 || x || y``.

        Both coordinates are 32 bytes because the field is 256 bits wide; the
        leading 0x04 is the SEC 1 tag for an uncompressed point.
        """

        return (
            b"\x04"
            + self._point[0].to_bytes(32, "big")
            + self._point[1].to_bytes(32, "big")
        )


class PrivateKey:
    """A secret scalar, with the matching public point derived on demand.

    The scalar must lie in ``1 <= secret < n``: zero has no inverse and is not a
    usable private key, and any value at or above the order is the same key as
    its residue, so accepting it would let two spellings of one key disagree.
    """

    def __init__(self, secret: int) -> None:
        if not isinstance(secret, int) or isinstance(secret, bool):
            raise ValueError("the private key must be an integer")
        if not 1 <= secret < P256_N:
            raise ValueError("the private key must satisfy 1 <= secret < n")
        self._secret = secret

    @property
    def secret(self) -> int:
        return self._secret

    @property
    def public_key(self) -> PublicKey:
        return PublicKey(_scalar_mult(self._secret, P256_G))


def generate_private_key(seed: bytes) -> PrivateKey:
    """Derive a private key from ``seed``, deterministically.

    The secret is ``sha256(seed) mod (n - 1) + 1``: the digest is folded into
    the valid range, and the ``+ 1`` maps the residue 0 to 1 so the result is
    never the forbidden zero. Deterministic derivation is what makes a test
    repeatable -- the same seed always yields the same key -- and it is
    deliberately not a source of entropy: a caller that needs an unpredictable
    key must seed this with one.
    """

    digest = sha256(seed)
    secret = int.from_bytes(digest, "big") % (P256_N - 1) + 1
    return PrivateKey(secret)


def sign(private_key: PrivateKey, digest: bytes, nonce: int) -> tuple[int, int]:
    """Return the ECDSA signature ``(r, s)`` of ``digest`` under ``nonce``.

    The nonce is supplied by the caller on purpose, so that a caller can reuse
    one and the nonce-reuse attack can be demonstrated against this exact
    function. A nonce outside ``1 <= nonce < n`` is rejected: zero has no
    inverse, and a value at or above the order is not the scalar the caller
    meant. The nonce is honoured as given -- nothing here replaces it.
    """

    if not isinstance(private_key, PrivateKey):
        raise ValueError("sign() needs a PrivateKey")
    if not isinstance(digest, (bytes, bytearray, memoryview)):
        raise ValueError("the digest must be bytes")
    if not isinstance(nonce, int) or isinstance(nonce, bool):
        raise ValueError("the nonce must be an integer")
    if not 1 <= nonce < P256_N:
        raise ValueError("the nonce must satisfy 1 <= nonce < n")
    digest = bytes(digest)

    z = digest_to_int(digest)
    point = _scalar_mult(nonce, P256_G)
    if point is None:
        raise ValueError("the nonce produced the point at infinity")
    r = point[0] % P256_N
    if r == 0:
        raise ValueError("the nonce produced r == 0")
    s = pow(nonce, -1, P256_N) * (z + r * private_key.secret) % P256_N
    if s == 0:
        raise ValueError("the nonce produced s == 0")
    return (r, s)


def sign_deterministic(private_key: PrivateKey, digest: bytes) -> tuple[int, int]:
    """Sign ``digest`` with the RFC 6979 nonce, so no randomness is needed.

    The nonce is drawn from :func:`_rfc6979_candidates`; if a candidate ever
    produced ``r == 0`` or ``s == 0`` the standard says to take the next one,
    which is the retry the loop below performs. That branch is unreachable for
    any realistic input but it is written down so the function is the standard's
    algorithm and not an approximation of it.
    """

    for nonce in _rfc6979_candidates(private_key, digest):
        try:
            return sign(private_key, digest, nonce)
        except ValueError:
            continue
    # Falling out of the loop returned None where a signature is promised, and a caller
    # unpacking it would fail somewhere else entirely with a message about a NoneType.
    # The branch is unreachable for any realistic input, which is exactly why it has to
    # say what happened rather than return nothing.
    raise ValueError("no valid nonce was found for this digest")


def verify(public_key: PublicKey, digest: bytes, signature: tuple[int, int]) -> bool:
    """Return whether ``signature`` is valid for ``digest`` under ``public_key``.

    Verification recomputes ``w = s^-1 mod n``, ``u1 = z*w`` and ``u2 = r*w``,
    and checks that ``u1*G + u2*Q`` has an x-coordinate congruent to r modulo n.
    A signature whose r or s is outside ``1 <= value < n`` is rejected before
    any arithmetic: it is not a signature at all, and inverting s would either
    fail or invert a value the standard never allowed. A malformed *argument*
    (a non-bytes digest, a signature that is not a pair) raises ValueError, the
    same convention every module here follows.
    """

    if not isinstance(public_key, PublicKey):
        raise ValueError("verify() needs a PublicKey")
    if not isinstance(digest, (bytes, bytearray, memoryview)):
        raise ValueError("the digest must be bytes")
    if not (isinstance(signature, tuple) and len(signature) == 2):
        raise ValueError("a signature must be a pair (r, s)")
    r, s = signature
    if not (isinstance(r, int) and isinstance(s, int)):
        raise ValueError("the signature values must be integers")
    if not (1 <= r < P256_N and 1 <= s < P256_N):
        return False
    digest = bytes(digest)

    z = digest_to_int(digest)
    w = pow(s, -1, P256_N)
    u1 = z * w % P256_N
    u2 = r * w % P256_N
    point = _point_add(
        _scalar_mult(u1, P256_G),
        _scalar_mult(u2, public_key._point),
    )
    if point is None:
        return False
    return point[0] % P256_N == r
